### ISSUE TITLE
Docker Container Crashes After Full Analysis of ~6-8 Photos

### ISSUE THREAD

**Issue by markziler** [HeyMaslo/companionserver#15]
I've had consistent problems with Docker crashing after processing about 6-8 photos from the smoke test library.

This occurs when pulling/running the Docker image from un1crom:
`docker run -p 41960:8080 un1crom/maslocompanionserver:1.0.4`

as well as after building a docker image locally:
`docker run -p 41960:8080 markziler/maslocompanionserver`
<img width="1152" alt="Docker screenshot" src="https://user-images.githubusercontent.com/68709045/91853891-ddae6280-ec30-11ea-9685-28bdbc4a7804.png">

When running the smoke-test javascript (on various image folders, and with various images included/excluded to control for any bad images choking the API), I get a consistent output JSON file with ~6-8 responses/rows.  See attached JSON output in zip file.  [smoke-test output.zip](https://github.com/HeyMaslo/companionserver/files/5156314/smoke-test.output.zip)

I have also tried the same thing using Postman with the same image being analyzed numerous times until a crash (both for local build as well as the pull from un1crom on Dockerhub).  I'm attaching a screenshot of the Postman request.  Also, I logged the response time for each call in case there was anything telling, but I do not see any patterns.
<img width="1271" alt="Postman Request" src="https://user-images.githubusercontent.com/68709045/91852605-10575b80-ec2f-11ea-8227-52f6053b2d4d.png">  The image being analyzed in this case was **https://www.dropbox.com/s/oyluukdws0rrihi/2020-08-21_22-04-46_UTC.jpg?dl=0**

- 1 - 14.8 seconds
- 2 - 21.18 s
- 3 - 11 s
- 4 - 12.14 s
- 5 - 14 s
- 6 - 17.34 s
- 7 - 16.93
- 8 - Docker container crashed.

The last error noted in the logs prior to the crash is below:

In particular, I've noted the following repeatedly:
Negative coordinates when cropping:
```
UnhandledPromiseRejectionWarning: RangeError: crop: x and y (x:375, y:-4) must be positive numbers
at Image.crop (/usr/src/app/node_modules/image-js/lib/image/transform/crop.js:52:11)
```
Type mismatch:
```
Error: The dtype of dict['ImageTensor'] provided in model.execute(dict) must be int32, but was float32
at Object.assert (/usr/src/app/node_modules/@tensorflow/tfjs-core/dist/tf-core.node.js:546:15)
at /usr/src/app/node_modules/@tensorflow/tfjs-converter/dist/tf-converter.node.js:5826:26
```

Last log output: 
```
(node:1) UnhandledPromiseRejectionWarning: RangeError: crop: x and y (x:375, y:-4) must be positive numbers
at Image.crop (/usr/src/app/node_modules/image-js/lib/image/transform/crop.js:52:11)
at Image._Image.default.<computed> [as crop] (/usr/src/app/node_modules/image-js/lib/image/core/extend.js:42:21)
at /usr/src/app/index.js:691:32
at Array.forEach (<anonymous>)
at imageObjectDetection (/usr/src/app/index.js:665:20)
at runMicrotasks (<anonymous>)
at processTicksAndRejections (internal/process/task_queues.js:97:5)
at async mediaParse (/usr/src/app/index.js:1352:30)
(node:1) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 10)
[Object: null prototype] {
originMediaID: 'Images/Gym/2020-08-22_02-23-33_UTC_1.jpg',
timeOut: '60000',
modelsToCall: '{"imageMeta": 1,"imageSceneOut": 1,"imageObjects": 1,"imageTox": 1,"imagePose": 1,"faces": 1,"photoManipulation": 1}'
}
{"imageMeta": 1,"imageSceneOut": 1,"imageObjects": 1,"imageTox": 1,"imagePose": 1,"faces": 1,"photoManipulation": 1}
124.8388671875
parsing now!
string
{"imageMeta": 1,"imageSceneOut": 1,"imageObjects": 1,"imageTox": 1,"imagePose": 1,"faces": 1,"photoManipulation": 1}
{
imageMeta: 1,
imageSceneOut: 1,
imageObjects: 1,
imageTox: 1,
imagePose: 1,
faces: 1,
photoManipulation: 1
}
object
{
mediaDominantColors: [ '#211d1b', '#cead96', '#795b4a', '#929687', '#8e8a94' ],
mediaImageResolution: { height: 1080, width: 1349 },
mediaColorComponents: 3,
mediaVisualFocus: { sharpness: 1.2894988327057546, entropy: 6.8869574681448285 },
mediaFileSize: 1456920,
mediaCompressionSize: 169592,
mediaCompressionPercentage: 0.7336309523809523
}
object
Tensor {
kept: false,
isDisposedInternal: false,
shape: [ 1349, 1080, 3 ],
dtype: 'int32',
size: 4370760,
strides: [ 3240, 3 ],
dataId: {},
id: 55922,
rankType: '3',
scopeId: 64694
}
http://localhost:8080/tensorflowlocal/deeplab/deeplab_pascal_1_default_1/model.json?tfjs-format=file
Error: The dtype of dict['ImageTensor'] provided in model.execute(dict) must be int32, but was float32
at Object.assert (/usr/src/app/node_modules/@tensorflow/tfjs-core/dist/tf-core.node.js:546:15)
at /usr/src/app/node_modules/@tensorflow/tfjs-converter/dist/tf-converter.node.js:5826:26
at Array.forEach (<anonymous>)
at GraphExecutor.checkInputShapeAndType (/usr/src/app/node_modules/@tensorflow/tfjs-converter/dist/tf-converter.node.js:5813:29)
at GraphExecutor.execute (/usr/src/app/node_modules/@tensorflow/tfjs-converter/dist/tf-converter.node.js:5527:14)
at GraphModel.execute (/usr/src/app/node_modules/@tensorflow/tfjs-converter/dist/tf-converter.node.js:6180:36)
at /usr/src/app/node_modules/@tensorflow-models/deeplab/dist/index.js:99:43
at /usr/src/app/node_modules/@tensorflow/tfjs-core/dist/tf-core.node.js:3075:22
at Engine.scopedRun (/usr/src/app/node_modules/@tensorflow/tfjs-core/dist/tf-core.node.js:3085:23)
at Engine.tidy (/usr/src/app/node_modules/@tensorflow/tfjs-core/dist/tf-core.node.js:3074:21)
{
timeOfDay: [
{ label: 'day', prob: 0.771184504032135 },
{ label: 'night', prob: 0.22881552577018738 }
],
mediaEstimatedCreationDate: 2018,
composition: undefined,
scenes: [
{
className: 'brassiere, bra, bandeau',
probability: 0.15473636984825134
},
{
className: 'jersey, T-shirt, tee shirt',
probability: 0.12707442045211792
},
{ className: 'comic book', probability: 0.07076089084148407 }
]
}
object
{ person: 1 }
{
objects: [ { bbox: [Array], class: 'person', score: 0.9024994969367981 } ],
personsColorPalette: [
[ 34, 30, 28 ],
[ 205, 170, 146 ],
[ 122, 90, 73 ],
[ 146, 150, 133 ],
[ 132, 140, 148 ]
],
isAnimal: {},
objectCountsbyClass: { person: 1 }
}
object
```

**Comment by un1crom** [comment]
@markziler @TianaCo @vitorbarros @rossingram @GregDav so what's going on here:

1. in the Deeplab model there is a bug in the open source library where the Tensor is the wrong type.  This had been corrected in previous builds of the companion server.  My suspicion is that in the 1.0.4 build something wasn't packaged correctly to use the corrected code.  NPMs that have been modified locally need to be specifically loaded locally and not pulled from NPM.  By default docker/node builds will attempted to get latest NPM from web.  You'll find that most the tensorflow models used were modified from their open source NPM ones to support LOCAL model storage and use, as per the desire to black box/make MCS usable out from the internet.  

So... look into rebuilding the MCS and using only the local modified tensorflow models.  in package.json you should see "devDependencies" ....

```
"http://localhost:8080/tensorflowlocal/deeplab/deeplab_pascal_1_default_1/model.json?tfjs-format=file
Error: The dtype of dict['ImageTensor'] provided in model.execute(dict) must be int32, but was float32"   
```

2.) The cropping error is because 
`UnhandledPromiseRejectionWarning: RangeError: crop: x and y (x:375, y:-4) must be positive numbers
at Image.crop (/usr/src/app/node_modules/image-js/lib/image/transform/crop.js:52:11)`

The face bounding box math to create crops for deeper analysis doesn't have good boundary conditions.  So inside the face model someone needs to look into how to guard rail against negative numbers.   just look for them and set them to something positive etc.  

3) Memory issues... generally, the memory in the node app will grow over successive runs do to tensorflow models sitting around in the "app memory"... we probably need to create a garbage collector that runs periodically in the app OR at the completion of every response.  The original design was meant to keep most things out of app memory but putting all the load up into every request may slow each request down.    

For considering... keep in mind that for every image submitted up to 12 copies of the image + all the models invoked will be loaded into memory....
