### ISSUE TITLE
Simplify Decisioning

### ISSUE THREAD

**Issue by markziler** [HeyMaslo/companionserver#6]
Remove all decisioning/curatorial reductions like "isAnimal" and primary/secondary face considerations

**Comment by un1crom** [comment]
isAnimal  @markziler is actually just a aggregate counter for the object detection of cat, dog or horse.  the full object detection output is already included in the json output.

**Comment by un1crom** [comment]
all the face details are rendered out too.

a client / user can determine if they do not like the APIs summary of primary and secondary faces.   

gender is looked at only for the first and second (primary and secondary face)... the resolution of gender is highly discouraged.  the output currently provides a two salience values that can be used as a gradient.  the resolution of salience to tag is discouraged for almost any real use due to model bias and the cultural sensitivity around gender and the very real issue that facial features do not accurately represent gender.
